modLoader="javafml"

loaderVersion="[28,)"

[[mods]]

modId="uniquee"

version="1.7.0"

displayName="Unique Enchantments"

credits="Thanks for this example mod goes to Java" #optional

authors="Speiger, Xaikii"
description='''
'''